### ISSUE TITLE
Update to 3.3.4 via Nuget crashes

### ISSUE THREAD

**Issue by digitalsigi** [devlooped/GitInfo#335]
## Describe the Bug

Updating to 3.3.4 crashes nuget updated

## Steps to Reproduce

1. Have 3.3.3 install 
2. Goto nuget packages for solution
3. Select gitinfo click on update

## Expected Behavior

No crash

## Exception with Stack Trace

```text
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.03.13.05.33.36/vulnerability.base.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.03.13.05.33.36/2024.03.13.05.33.36/vulnerability.update.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass20_0.<<ExecuteActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__32.MoveNext()
Time Elapsed: 00:00:01.0336326
```

## Version Info

Installed GitInfo 3.3.3

**Comment by kzu** [comment]
Can't repro with:

```
Microsoft Visual Studio Enterprise 2022
Version 17.10.0 Preview 2.0
VisualStudio.17.Preview/17.10.0-pre.2.0+34707.107
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA940
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.10.173.6507
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.10.173.6507
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.10.173.6507
Azure Functions and Web Jobs Tools

C# Tools   4.10.0-3.24127.5+e3d617bc46b0f92c2d2438188b35e009b942d0d1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

File Explorer   1.0.61
Gives access to all files and folders from the file system under the repo- or solution root folder. All in the same Solution Explorer view.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

GitHub Copilot   1.156.0.0 (v1.156.0.0@82fafb995)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.156.0

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.5.238
2.5.238

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

Razor (ASP.NET Core)   17.10.2.2415507+c5753a9c23d8422e24ed842c0ddad71e84d900d1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.10.87.0
Microsoft SQL Server Data Tools

Tweaks 2022   1.1.143
A collection of minor fixes and tweaks for Visual Studio to reduce the paper cuts and make you a happier developer

TypeScript Tools   17.0.30221.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.10.0-3.24127.5+e3d617bc46b0f92c2d2438188b35e009b942d0d1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.10.0-beta.24127.3+b57dee7cec971021547a7b8a36a46d7271fea99e
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VSColorOutput64   2023.4
Color output for build and debug windows - https://mike-ward.net/vscoloroutput
```
